'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from './providers'
import Nav from '../components/NavBar'
import { Box } from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Am I the Jerk',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Nav />
          <Box paddingX="350" paddingY="10" bg={'transparent'}>
            {children}
          </Box>
        </Providers>
      </body>
    </html>
  )
}
